name: Publish

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  lint-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        env:
          OUTPUT: CHANGELOG.md

      - name: Verify no changes to CHANGELOG.md
        run: |
          if ! git diff --exit-code; then
          echo 'Changes detected to the CHANGELOG.md, you must generate the CHANGELOG.md with `git cliff` and commit the changes.'
          exit 1
          fi

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: lint-changelog
    steps:
      - uses: actions/checkout@v4
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Publish to crates.io
        run: |
          cargo publish --package tiny-orm-model
          cargo publish --package tiny-orm-macros --features sqlite
          cargo publish --package tiny-orm --features sqlite
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
